### ISSUE TITLE
Error: certificate signature failure

### ISSUE THREAD

**Issue by siddjain** [ldapjs/node-ldapjs#512]
we are getting above error when trying to connect to an openldap server. our complete code is as follows and modeled after [1](https://github.com/joyent/node-ldapjs/issues/326#issuecomment-427022915):

```js
var ldap = require("ldapjs");
var fs = require("fs");
const assert = require("assert");
var client = ldap.createClient({
        url: "ldap://jnj-ldap-server:389/dc=jnj,dc=com",
        tlsOptions: opts
});
var opts = {
  ca: [fs.readFileSync("jnj-ca-chain.pem")],
  // Necessary only if the server requires client certificate authentication.
  key: fs.readFileSync('jnj-web-app-tls.key'),
  cert: fs.readFileSync('jnj-web-app-tls.pem'),  
  host: "jnj-ldap-server",
  ecdhCurve: 'auto', // see https://github.com/nodejs/node/issues/16196 and https://github.com/joyent/node-ldapjs/issues/464
};
var controls = client.controls;
var dn = "cn=admin,dc=jnj,dc=com";
var password = "superman";
client.starttls(opts, controls, function(err, res) {
  assert.ifError(err);
  client.bind(dn, password, function (err) {
        assert.ifError(err);
    });
    log.info("StartTTLS connection established.")
  // Client communication now TLS protected
});
```

output:
```sh
root@6fc2ae248018:/usr/src/app# node app.js
assert.js:816
assert.ifError = function ifError(err) { if (err) throw err; };
                                                  ^

Error: certificate signature failure
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
```

on server logs we see this:
```sh
5cb79962 conn=1008 fd=12 ACCEPT from IP=x.x.x.x:59212 (IP=0.0.0.0:389)
5cb79962 conn=1008 op=0 EXT oid=1.3.6.1.4.1.1466.20037
5cb79962 conn=1008 op=0 STARTTLS
5cb79962 conn=1008 op=0 RESULT oid= err=0 text=
TLS: can't accept: (unknown error code).
5cb79962 conn=1008 fd=12 closed (TLS negotiation failure)
```

our server is started as explained in https://github.com/osixia/docker-openldap#use-your-own-certificate

How can we fix this? we tried changing `url` to use `ldaps` and `636` but that gives another error

Further diagnostics:

```sh
root@6fc2ae248018:/usr/src/app# openssl s_client -state -nbio -connect jnj-ldap-server:389 -CAfile jnj-ca-chain.pem
CONNECTED(00000003)
Turned on non blocking io
SSL_connect:before SSL initialization
SSL_connect:SSLv3/TLS write client hello
SSL_connect:error in SSLv3/TLS write client hello
write R BLOCK
SSL_connect:error in SSLv3/TLS write client hello
read:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1555543109
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

```sh
siddjain@jnj:~/temp$ openssl verify -CAfile jnj-ca-chain.pem jnj-ldap-server-tls.pem
jnj-ldap-server-tls.pem: OK
```

if clientauth is disabled on the server by setting `LDAP_TLS_VERIFY_CLIENT=never`, we still get same output on client:

```sh
root@6fc2ae248018:/usr/src/app# openssl s_client -state -nbio -connect jnj-ldap-server:389 -CAfile jnj-ca-chain.pem
CONNECTED(00000003)
Turned on non blocking io
SSL_connect:before SSL initialization
SSL_connect:SSLv3/TLS write client hello
SSL_connect:error in SSLv3/TLS write client hello
write R BLOCK
SSL_connect:error in SSLv3/TLS write client hello
read:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1555544943
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

```sh
root@6fc2ae248018:/usr/src/app# node app.js
assert.js:816
assert.ifError = function ifError(err) { if (err) throw err; };
                                                  ^
Error: certificate signature failure
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
root@6fc2ae248018:/usr/src/app# 
```
but on server we see this:
```sh
5cb7bbba conn=1001 fd=12 ACCEPT from IP=x.x.x.x:40946 (IP=0.0.0.0:389)
5cb7bbba conn=1001 op=0 EXT oid=1.3.6.1.4.1.1466.20037
5cb7bbba conn=1001 op=0 STARTTLS
5cb7bbba conn=1001 op=0 RESULT oid= err=0 text=
5cb7bbba conn=1001 fd=12 TLS established tls_ssf=128 ssf=128
5cb7bbba conn=1001 fd=12 closed (connection lost)
```

**Comment by jsumners** [comment]
It looks like you are using a TLS v1.2 certificate on your server (as you should). Unfortunately, this is not going to work until `ldapjs` supports Node >= 10. Please track issue #524. Once a new release is out that supports Node 10, please try again and open a new issue if it is still a problem.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
