### ISSUE TITLE
 Parser error Expected 0x2: got 0x3

### ISSUE THREAD

**Issue by shimondoodkin** [ldapjs/node-ldapjs#516]
```text

new connection from 127.0.0.1:64820

Parser.write data= 

16030300a10100009d03035cc6e3da99e977df74a77db770df433da044f81b46ff42c120c27efeb5c83f4000003ac023c027003cc025c02900670040c009c013002fc004c00e00330032c02bc02f009cc02dc031009e00a2c008c012000ac003c00d0016001300ff0100003a000a001600140017001800190009000a000b000c000d000e0016000b00020100000d001600140603060105030501040304010402020302010202

events.js:167
      throw er; // Unhandled 'error' event
      ^
VError: Parser error for 127.0.0.1:64820: Expected 0x2: got 0x3
    at Parser.<anonymous> (C:\files\Tools\ldaptestserver\node_modules\ldapjs\lib\server.js:442:26)
    at Parser.emit (events.js:182:13)
    at Parser.write (C:\files\Tools\ldaptestserver\node_modules\ldapjs\lib\messages\parser.js:108:10)
    at Socket.<anonymous> (C:\files\Tools\ldaptestserver\node_modules\ldapjs\lib\server.js:460:16)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Emitted 'error' event at:
    at Parser.<anonymous> (C:\files\Tools\ldaptestserver\node_modules\ldapjs\lib\server.js:442:12)
    at Parser.emit (events.js:182:13)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by jsumners** [comment]
Can you provide a reproducible test case?

**Comment by jsumners** [comment]
Closing due to inactivity. If this is still an issue for you and you can provide a reproducible test case feel free to re-open.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
