### ISSUE TITLE
Searching an attribute's exact value with '(' character now needs an extra '\' character to be included before it. Worked fine in previous versions

### ISSUE THREAD

**Issue by hkhandelwal4** [ldapjs/node-ldapjs#564]
illegal unescaped char: (
    at escapeValue (c:\api\node_modules\ldap-filter\lib\index.js:49:13)
    at parseExpr (c:\api\node_modules\ldap-filter\lib\index.js:167:16)
    at parseFilter (c:\api\node_modules\ldap-filter\lib\index.js:228:14)
    at Object.parse (c:\api\node_modules\ldap-filter\lib\index.js:252:18)
    at Object.parseString (c:\api\node_modules\ldapjs\lib\filters\index.js:181:27)
    at Client.search (c:\api\node_modules\ldapjs\lib\client\client.js:559:30)
    at client.bind (c:\api\dist\ldap-manager\ldap-manager.js:185:28)
    at sendResult (c:\api\node_modules\ldapjs\lib\client\client.js:1168:12)
    at messageCallback (c:\api\node_modules\ldapjs\lib\client\client.js:1191:16)
    at Parser.onMessage (c:\api\node_modules\ldapjs\lib\client\client.js:869:14)

**Comment by jsumners** [comment]
There is not nearly enough information in this issue to even begin answering it.

What is some example code that triggers the problem? What version do you claim "worked fine"? What version are you claiming does not work?

**Comment by UziTech** [comment]
This is a [breaking change](https://github.com/pfmooney/node-ldap-filter/blob/master/CHANGES.md#030) from ldap-filter 

> While the old parser would tolerate unescaped characters in the ()\* set, the new parser requires them to be escaped via the \XX hex notation

ldapjs@2.0.0 changes escaped characters to their hex notation automatically in #521 but they must be escaped with `\`.

https://github.com/ldapjs/node-ldapjs/blob/a113953e0d91211eb945d2a3952c84b7af6de41c/lib/filters/index.js#L167-L177

**Comment by hkhandelwal4** [comment]
In case of v1.0.2, i was searching list of all users having display name equal to a given string using below filter:

const displayName: string = **"Khandelwal, H. (Himanshu)"**;
const opts: ldapjs.SearchOptions = {
                            attributes: ['displayName'],
                            filter: `(displayName=${displayName})`,
                            scope: 'sub',
                        };
But after updating it to latest version v2.0.0-pre.2, i have to use escape character to search the same name
const displayName: string = **"Khandelwal, H. \\(Himanshu\\)"**;
const opts: ldapjs.SearchOptions = {
                            attributes: ['displayName'],
                            filter: `(displayName=${displayName})`,
                            scope: 'sub',
                        };

**Comment by hkhandelwal4** [comment]
@UziTech Thanks for clearing it, will update code accordingly :)

**Comment by shilpa0208** [comment]
This is still an issue with ldap-filter

**Comment by UziTech** [comment]
@shilpa0208 yes you must escape  the characters `(`, `)`, `*` with a backslash (`\`)

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
