### ISSUE TITLE
Error when run with --use_strict mode

### ISSUE THREAD

**Issue by niclasek** [ldapjs/node-ldapjs#607]
I get the following error on client.search when running node in strict mode
```
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at _assert (C:\Users\niclas.ek\repos\keydom\node_modules\ldapjs\node_modules\ldap-filter\node_modules\assert-plus\assert.js:41:50)
    at Object.string (C:\Users\niclas.ek\repos\keydom\node_modules\ldapjs\node_modules\ldap-filter\node_modules\assert-plus\assert.js:160:9)
    at Object.parse (C:\Users\niclas.ek\repos\keydom\node_modules\ldapjs\node_modules\ldap-filter\lib\index.js:420:12)
    at Object.parseString (C:\Users\niclas.ek\repos\keydom\node_modules\ldapjs\lib\filters\index.js:176:25)
    at Client.search (C:\Users\niclas.ek\repos\keydom\node_modules\ldapjs\lib\client\client.js:769:30)
```

There is a bug in assert-plus version 0.1.5 used by ldap-filter version 0.2.2 used in the version 1.0.2 of ldapjs. See here: https://github.com/joyent/node-assert-plus/issues/23

The latest version of ldap-filter (v0.3.3) uses the dependency "assert-plus": "^1.0.0" in which this bug is resolved. 

I have edited the package.json manually to use the version 0.3.3 of ldap-filter and this resolves my issue. I'm not sure if that introduces other bug though. 

Could you evaluate upgrading the dependency ldap-filter to the latest version?

**Comment by jsumners** [comment]
1. Use `ldapjs@next`
2. I do not recommend using the `--use_strict` flag. Wherever you want strict mode, simply add a `'use strict'` to the top of your source file. Using the Node switch enforces it across _all_ source files and your dependencies, as you have learned, may not work correctly as a result.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
