### ISSUE TITLE
LDAPS. Connecting Ldap over SSL

### ISSUE THREAD

**Issue by omairnabiel** [ldapjs/node-ldapjs#628]
I've added the certificates and Domain Controller Active Directory Services and verified it using ldp.exe. Now While connecting to ldap server over SSL I'm using the following url

`ldaps://my.ip.address/:636`

But getting the following error

`
{"error":{"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"},"level":"error","message":"uncaughtException: unable to verify the first certificate\nError: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n
`
Do I have to attach the certificate on client side as well. How do I use it with ldapjs?

**Comment by omairnabiel** [comment]
I'm able to solve with by passing ` tlsOptions: { rejectUnauthorized: false }` in the createClient

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
