### ISSUE TITLE
rebind after client.destroy()

### ISSUE THREAD

**Issue by Gr4ph1xZ** [ldapjs/node-ldapjs#633]
Hello,

i always got the error 'ECONNRESET' (about 15min after the start of my node.js application) using ldapjs. To fix this I tried to use client.destroy() in my callback function and when I need the ldapClient again create and bind it new.

```js
var ldapClient = undefined;

    function ldapCreate() {
      ldapClient = undefined;
      ldapClient = ldap.createClient({
        url: 'ldap://server.com:3268',
        reconnect: true
      });

      ldapClient.bind('CN=commonname,CN=Users,DC=domaincontroller,DC=de', 'password', function(err) {
        if (err) {
          console.log("\x1b[41m%s\x1b[0m", 'LDAP bind failed! (' + err + ')');
          process.exit(0);
        } 
      });
    }

    ldapCreate();
    setTimeout(function() {
      var methodStatus;
      var f = '(&(userprincipalname=' + email + ')(memberof=Group,OU=Anwendung,OU=Gruppen,OU=Operatoren,DC=domaincontroller,DC=de))';
      var ldapObject;

      var opts = {
        filter: f,
        scope: 'sub'
      };
      ldapClient.search('OU=Benutzer,OU=Operatoren,DC=domaincontroller,DC=de', opts, function(err, res) {
        res.on('searchEntry', function(entry) {
          var userClient = ldap.createClient({
            url: 'ldap://server.com:3268'
          });

          userClient.bind(entry.object.dn + '', password + '', function(err) {
            if (err) {
              methodStatus = false;
            } else {
              methodStatus = true;
            }
            userClient.destroy();
          });
          ldapObject = entry.object;

        });
        ldapClient.destroy();
      });
}, 1000);
```

The Problem now is, that I can't create the ldapClient the second time:

```js
ConnectionError: 3__ldap://server.com:3268 closed
    at /var/www/srv/node_modules/ldapjs/lib/client/client.js:1062:17
    at /var/www/srv/node_modules/ldapjs/lib/client/message-tracker/index.js:113:7
    at Map.forEach (<anonymous>)
    at Object.purgeMessages [as purge] (/var/www/srv/node_modules/ldapjs/lib/client/message-tracker/index.js:110:14)
    at Client._onClose (/var/www/srv/node_modules/ldapjs/lib/client/client.js:1060:11)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  lde_message: '3__ldap://server.com:3268 closed',
  lde_dn: null
}
```

**Comment by jsumners** [comment]
You shouldn't be using a `setTimeout` to determine when the client has been created and the connection established. You should be using the callback to trigger the code that runs after the connection is created.

**Comment by Gr4ph1xZ** [comment]
> You shouldn't be using a `setTimeout` to determine when the client has been created and the connection established. You should be using the callback to trigger the code that runs after the connection is created.

I tried it like this:

```
var ldapClient = undefined;

    function ldapCreate() {

      return new Promise(resolve => {

        ldapClient = undefined;
        ldapClient = ldap.createClient({
          url: 'ldap://server.com:3268',
          reconnect: true
        });


        ldapClient.bind('CN=xx,CN=Users,DC=xx,DC=de', 'xx', function(err) {
          if (err) {
            console.log("\x1b[41m%s\x1b[0m", 'LDAP bind failed! (' + err + ')');
            process.exit(0);
            resolve(false);
          } else {
            resolve(true);
          }
        });
      });
    }


    ldapCreate();
    if (await ldapCreate()) {
      var methodStatus;
      var f = '(&(userprincipalname=' + email + ')(memberof=xx,OU=Anwendung,OU=Gruppen,OU=Operatoren,DC=xx,DC=de))';
      var ldapObject;

      var opts = {
        filter: f,
        scope: 'sub'
      };
      ldapClient.search('OU=Benutzer,OU=Operatoren,DC=xx,DC=de', opts, function(err, res) {
        res.on('searchEntry', function(entry) {
          var userClient = ldap.createClient({
            url: 'ldap://scharrnet.de:3268'
          });

          userClient.bind(entry.object.dn + '', password + '', function(err) {
            if (err) {
              methodStatus = false;
            } else {
              methodStatus = true;
            }
            userClient.destroy();
          });
          ldapObject = entry.object;

        });
        ldapClient.destroy();
      });
}
```

But I get this error:

```
ConnectionError: 5__ldap://server.com:3268 closed
    at /var/www/srv/node_modules/ldapjs/lib/client/client.js:1062:17
    at /var/www/srv/node_modules/ldapjs/lib/client/message-tracker/index.js:113:7
    at Map.forEach (<anonymous>)
    at Object.purgeMessages [as purge] (/var/www/srv/node_modules/ldapjs/lib/client/message-tracker/index.js:110:14)
    at Client._onClose (/var/www/srv/node_modules/ldapjs/lib/client/client.js:1060:11)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  lde_message: '5__ldap://server.com:3268 closed',
  lde_dn: null
}
```

**Comment by jsumners** [comment]
You're calling your `ldapCreate` function twice. The first time without waiting for a result.

In your `search` callback you are destroying the connection potentially before you are done processing search entries. And your search entry handler creates a new connection that doesn't use the callback, or connection events, to determine the connection has been made.

If you can create a minimal reproduction of your issue against our LDAP server container -- https://github.com/ldapjs/docker-test-openldap/packages/28837 -- then I will continue looking. Otherwise, I do not have time to go back and forth with dart throwing.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
