### ISSUE TITLE
Error: urlStr + ' is an invalid LDAP url (scope)'

### ISSUE THREAD

**Issue by ashishjindal13** [ldapjs/node-ldapjs#653]
Hi, I am using this very simple code to connect to LDAP but no matter what i keep on getting the following error: 

```js
var ldap = require('ldapjs'); 
var client = ldap.createClient({url:'ldap://openam.sandbox.local:10389'}); 
client.bind('cn=DM', 'test', function(err) {
  if (err){
    console.log("not able to connect")
  }     else      { 
    console.log("connected successfully")
  }
});
```

I am using mac. 

```
/Users/ashishjindal/Projects/sw-app-api/api-testing/node_modules/ldapjs/lib/url.js:15
      throw new TypeError(urlStr + ' is an invalid LDAP url (scope)')
      ^

TypeError: ldap://openam.sandbox.local:10389 is an invalid LDAP url (scope)
    at Object.parse (/Users/ashishjindal/Projects/sw-app-api/api-testing/node_modules/ldapjs/lib/url.js:15:13)
    at new Client (/Users/ashishjindal/Projects/sw-app-api/api-testing/node_modules/ldapjs/lib/client/client.js:114:33)
    at Object.createClient (/Users/ashishjindal/Projects/sw-app-api/api-testing/node_modules/ldapjs/lib/client/index.js:17:12)
    at Object.<anonymous> (/Users/ashishjindal/Projects/sw-app-api/api-testing/tests/builders/ldap.js:3:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

[Done] exited with code=1 in 0.148 seconds
```

**Comment by ashishjindal13** [comment]
this looks like a problem with my mac, i executed the same code on another system on windows and it worked fine.

**Comment by Acetylen3** [comment]
I got the same issue.
The actual exception has been thrown away because of the catch handling just return a message "TypeError(urlStr + ' is an invalid LDAP url (scope)')".
The real issue is because there is a error at url.js:13 
Exception: TypeError: url.URL is not a constructor 

The detail explanation is here: https://github.com/ConsenSys/armlet/issues/105#issuecomment-673060135

However, I don't know how to resolve it.

**Comment by jsumners** [comment]
TypeScript has nothing to do with this error. If you are seeing this error it is almost certainly due to an unsupported version of Node.js being used.

**Comment by Acetylen3** [comment]
> TypeScript has nothing to do with this error. If you are seeing this error it is almost certainly due to an unsupported version of Node.js being used.

Thank you for your reply.
I don't use typescript in my project, however, I found the @types/node package is coming from 'react-scripts'

reactproject2@0.1.0 C:\Users\user\Documents\repository\web-app
`-- react-scripts@3.4.3
  `-- webpack-dev-server@3.11.0
    `-- del@4.1.1
      `-- @types/glob@7.1.3
        `-- @types/node@14.11.10

**Comment by jsumners** [comment]
We do not support TypeScript in any form. If you have issues with a TypeScript package, please take it up with the author of that package.

**Comment by Acetylen3** [comment]
> We do not support TypeScript in any form. If you have issues with a TypeScript package, please take it up with the author of that package.

I'm don't want to due with typescript neither.
For the record. I'm using node v10.23.0 with following packages:
"dependencies": {
    "@date-io/date-fns": "^1.3.13",
    "@material-ui/core": "^4.11.1",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/pickers": "^3.2.10",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "activedirectory2": "^2.1.0",
    "ajv": "^6.12.6",
    "date-fns": "^2.16.1",
    "querystring-browser": "^1.0.4",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.1"
  },

When the following code is run:
const url = require('url')
parsedURL = new url.URL(ldapurl)

I got this error:
Unhandled Rejection (TypeError): url.URL is not a constructor

However, because of the exception was caught and thrown again as"throw new TypeError(urlStr + ' is an invalid LDAP url (scope)')"
I always got the same error, disregarding what URL that I has passed.

I've yet resolve this problem.

**Comment by jsumners** [comment]
![image](https://user-images.githubusercontent.com/321201/100636744-03b2d400-3300-11eb-8f4d-a414df607b89.png)

**Comment by JohnGrat** [comment]
i got it working my changing url.URL to url.Parse
      parsedURL = new url.parse(urlStr)
//parsedURL = new url.URL(urlStr)
    } catch (error) {

**Comment by jsumners** [comment]
`URL.parse` has been deprecated since Node.js 11 -- https://nodejs.org/dist/latest-v14.x/docs/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost

`URL.URL` was added in Node.js 10 -- https://nodejs.org/dist/latest-v14.x/docs/api/url.html#url_class_url

Please provide a minimal reproduction if you are encountering this error with Node.js >= 10 and ldapjs >= 2.

**Comment by JD2k** [comment]
Had the same problem with using webpack. After adding nodeExternals (https://github.com/liady/webpack-node-externals) to webpack.config.js. Everything worked fine out of the box.

**Comment by pchoudhary17** [comment]
> `URL.parse` has been deprecated since Node.js 11 -- https://nodejs.org/dist/latest-v14.x/docs/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost
> 
> `URL.URL` was added in Node.js 10 -- https://nodejs.org/dist/latest-v14.x/docs/api/url.html#url_class_url
> 
> Please provide a minimal reproduction if you are encountering this error with Node.js >= 10 and ldapjs >= 2.

I'm using ldapjs 2.3.3 and node 18.12.0 but still encoutering the same error in ldap.createClient.
I tried to console log url.parse and that works but url.URL seems to not.  while parsing using URL hostname and port are null and everyting is getting added to pathname only.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
