### ISSUE TITLE
ldap.js TypeError: name (string) required at Client.bind

### ISSUE THREAD

**Issue by kamidehlvi** [ldapjs/node-ldapjs#661]
Hi, I am using ldap.js  for normal client bind its work properly. But when use promise to return status it gives _TypeError: name (string) required at Client.bind_
 
Please help me how can I get the response from the promise in call back function of client.bind and send the status to redirect page.
Regards,

**Node Js Code :**
```js
app.post('/authenticate',function(req,res)
{
 
  var client = ldap.createClient({url: 'ldap://195.95.5.40:389'});
  console.log(JSON.stringify(req.body));
  var obj = JSON.parse(JSON.stringify(req.body));
  console.log(obj.UserName);
  console.log(obj.Pwd);
  var username = obj.UserName;
  var password = obj.Pwd;
  var DomainFulname = 'CN='+ username +',CN=Users,DC=capture,DC=net';
  console.log( " domain full path : " + DomainFulname);
  console.log ( "password : " + password) 
  

  if (password != null && password != '')
    {
          client.bind(DomainFulname.trim(), password.trim(), function (err,res){
            return new Promise((resolve,reject) =>{
            setTimeout(function(){
              if (err)            
              {
                console.log("Domain Authectication Failed as error : " + err.message);
                resolve('Error');
              }
            else
            {
              console.log('Sucessfully binded');
              resolve('Done');
            }

            },300);
                  
                                   });
        });
      }
      client.bind().then(text=>{
      console.log(text);
     });
});
```

**Output :**
```
C:\Users\kami\Documents\newCapture>node index.js
newCapture app listening on port 5001!
{"UserName":"asdas","Pwd":"xcfsdf"}
asdas
xcfsdf
 domain full path : CN=asdas,CN=Users,DC=capture,DC=net
password : xcfsdf
TypeError: name (string) required
    at Client.bind (C:\Users\kami\Documents\newCapture\node_modules\ldapjs\lib\client\client.js:270:71)
    at C:\Users\kami\Documents\newCapture\index.js:107:14
    at Layer.handle [as handle_request] (C:\Users\kami\Documents\newCapture\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\kami\Documents\newCapture\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\kami\Documents\newCapture\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\kami\Documents\newCapture\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\kami\Documents\newCapture\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\kami\Documents\newCapture\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\kami\Documents\newCapture\node_modules\express\lib\router\index.js:275:10)
    at serveStatic (C:\Users\kami\Documents\newCapture\node_modules\serve-static\index.js:75:16)
Domain Authectication Failed as error : 80090308: LdapErr: DSID-0C0903AA, comment: AcceptSecurityContext error, data 525, v1772
```

**Comment by jsumners** [comment]
You would need to write a new function that wraps bind:

```js
function promise(resolve, reject) {
  client.bind(dn, passwd, (err, res) => {
    if (err) return reject(err)
    // handle res events and eventually:
    resolve()
  })
}

(new Promise(promise)).then(connected).catch(boom)
```

**Comment by kamidehlvi** [comment]
hi, Jsumners thank you for your reply
can you please map this with real scenario which I have mentioned **I am new to functional and arrow based function programming?**
Unable to understand how to pass paraments to this bind function as promise function takes only reject and resolve similarly how can I get the result in JSON or plane function string to calling function.
\please help I am very confused.
Regards,

**Comment by jsumners** [comment]
Sorry, this is not a general JavaScript help forum. Please visit https://stackoverflow.com for help with general programming questions.

**Comment by kamidehlvi** [comment]
You are right it is not a development forum, but I think this is "call back hall" problem. Instead of code snipped can you please identify the reason of  "TypeError: name (string) required"  when code call client.bind function.

**Comment by kamidehlvi** [comment]
function promise(resolve, reject) {
  client.bind(dn, passwd, (err, res) => {
    if (err) return reject(err)
    // handle res events and eventually:
    resolve()
  })
}

(new Promise(promise)).then(connected).catch(boom)

Here in the given code settimeout function is not available, that is also required please.

**Comment by jsumners** [comment]
I answered the question in my original response. You are mixing promise based code with callback based code in an incorrect way.

**Comment by syedhammadsibtain** [comment]
```
app.post('/authenticate',function(req,res)
{
 
  var client = ldap.createClient({url: 'ldap://195.95.5.40:389'});
  var obj = req.body;
  var DomainFulname = 'CN='+ obj.UserName +',CN=Users,DC=capture,DC=net';

  if (obj.Pwd != null && obj.Pwd != '') {
        client.bind(DomainFulname.trim(), obj.Pwd.trim(), function (err,res){
            if(err) {
				return res.json({message: 'Some Error Occured', err: err});
			}
			res.json({message: 'Success'});
        });
  } else {
	  res.json({message: 'Please Provide Password'});
  }
});
```

**Comment by kamidehlvi** [comment]
Thank you for your response  syedhammadsibtain!
Unfortunately it gives this error
C:\Users\kami\Documents\newCapture\index.js:126
                                return res.json({message: 'Some Error Occured', err: err});
                                           ^

TypeError: Cannot read property 'json' of undefined

**Comment by jsumners** [comment]
This thread is off topic. Please take it to a more appropriate location.
