### ISSUE TITLE
Adding new users to a group

### ISSUE THREAD

**Issue by larrybg** [ldapjs/node-ldapjs#665]
I can successfully create a user but have a problem with adding it to a group. What am I doing wrong? Can you please provide an example of how to add a new user to a group with `ldapjs`?

```
async function createLDAPAccount(newUser) {
  return new Promise((resolve, reject) => {
    var BASE = "OU=TeamA,OU=center,DC=lab,DC=comp,DC=local";
    let ldapURL = appSettings.getLDAPUrl();
    var tlsOptions = { rejectUnauthorized: false };
    var client = ldapjs.createClient({
      url: ldapURL,
      tlsOptions: tlsOptions,
    });

    client.bind('CN=admin-user,ou=Admin,OU=center,DC=lab,DC=comp,DC=local', 'pass', function (err) {

      if (err) return reject(err);

      let userID = newUser.firstname.toLowerCase().charAt(0) + newUser.lastname.toLowerCase();
      var newDN = "cn=" + newUser.firstname + " " + newUser.lastname + "," + BASE;

      var newLDAPUser = {
        uid: userID,
        sAMAccountName: userID,
        cn: newUser.firstname + " " + newUser.lastname,
        givenName: newUser.firstname,
        sn: newUser.lastname,
        displayName: newUser.firstname + " " + newUser.lastname,
        userPrincipalName: userID + '@lab.comp.local',
        mail: newUser.email,
        memberOf: 'CN=TeamA,OU=center,DC=lab,DC=comp,DC=local',
        info: 'defaultVmFolder=' + newUser.firstname + " " + newUser.lastname,
        objectClass: 'user',
        unicodePwd: encodePassword('MyNewPassword12345'),
        userAccountControl: '512'
      };


      client.add(newDN, newLDAPUser, function (err, response) {
        if (err) {
          console.log(err);
          return reject(err);
        }
        else {
          return resolve(response);
        }
      });
    });

  });
}
```

The error message I'm receiving is: 
```
node_internals>/internal/process/warning.js:32
module.exports.<computed> {lde_message: '0000209A: SvcErr: DSID-031A101A, problem 5003 (WILL_NOT_PERFORM), data 0
', lde_dn: null, stack: 'UnwillingToPerformError: 0000209A: SvcErr: DS…Read (internal/stream_base_commons.js:186:23)'}
routes/userManagerRoute.js:117
get code:ƒ getCode() { return CODES[code]; }
53
get dn:ƒ getDN() {\n      return (this.lde_dn ? this.lde_dn.toString() : '');\n    }
''
lde_dn:null
lde_message:'0000209A: SvcErr: DSID-031A101A, problem 5003 (WILL_NOT_PERFORM), data 0\n'
get message:ƒ getMessage() {\n      return this.lde_message || this.name;\n    }
'0000209A: SvcErr: DSID-031A101A, problem 5003 (WILL_NOT_PERFORM), data 0
'
get name:ƒ getName() { return err; }
'UnwillingToPerformError'
stack:'UnwillingToPerformError: 0000209A: SvcErr: DSID-031A101A, problem 5003 (WILL_NOT_PERFORM), data 0\n\n    at messageCallback (/Users/larry.bakun@us.ibm.com/Documents/GitHub/node.js/soar_vm_manager/node_modules/ldapjs/lib/client/client.js:1419:45)\n    at Parser.onMessage (/Users/larry.bakun@us.ibm.com/Documents/GitHub/node.js/soar_vm_manager/node_modules/ldapjs/lib/client/client.js:1089:14)\n    at Parser.emit (events.js:310:20)\n    at Parser.write (/Users/larry.bakun@us.ibm.com/Documents/GitHub/node.js/soar_vm_manager/node_modules/ldapjs/lib/messages/parser.js:111:8)\n    at TLSSocket.onData (/Users/larry.bakun@us.ibm.com/Documents/GitHub/node.js/soar_vm_manager/node_modules/ldapjs/lib/client/client.js:1076:22)\n    at TLSSocket.emit (events.js:310:20)\n    at addChunk (_stream_readable.js:286:12)\n    at readableAddChunk (_stream_readable.js:268:9)\n    at TLSSocket.Readable.push (_stream_readable.js:209:10)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)'
```

**Comment by jsumners** [comment]
Have you researched the error? https://duckduckgo.com/?q=problem+5003+(WILL_NOT_PERFORM)

**Comment by larrybg** [comment]
Hey @jsumners. Yes, I did. It looks like you cannot create a new user and add it to a group in one step. This helped me as a second step to assign a group to a user: https://stackoverflow.com/questions/32597540/how-to-add-user-to-an-ldap-group-with-ldap-js

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
