### ISSUE TITLE
Read ECONNRESET error

### ISSUE THREAD

**Issue by regicsolutions** [ldapjs/node-ldapjs#718]
I am getting this error when enabling  the same Docker container that works  QA but not in prod.                                                           ? events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Client instance at:
    at Backoff.<anonymous> (/opt/app-root/src/node_modules/ldapjs/lib/client/client.js:1036:12)
    at Backoff.emit (events.js:315:20)
    at Backoff.EventEmitter.emit (domain.js:467:12)
    at Backoff.backoff (/opt/app-root/src/node_modules/backoff/lib/backoff.js:41:14)
    at /opt/app-root/src/node_modules/ldapjs/lib/client/client.js:1020:15
    at f (/opt/app-root/src/node_modules/once/once.js:25:25)
    at TLSSocket.onResult (/opt/app-root/src/node_modules/ldapjs/lib/client/client.js:810:7)
    at Object.onceWrapper (events.js:422:26)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by UziTech** [comment]
The `ECONNRESET` error means the server closed the connection. Without knowing more about the server I don't know how we could help. Could be a permissions issue or some hop between production and ldap server screwing something up.

**Comment by regicsolutions** [comment]
@UziTech any idea what protocol the package makes use of to make the connection?

**Comment by jsumners** [comment]
TCP. LDAP is based on TCP.

**Comment by regicsolutions** [comment]
Ended up being an egress network policy that was blocking my ldap traffic, appreciate the help gents!

**Comment by jsumners** [comment]
Glad you found the issue.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
