### ISSUE TITLE
Error: modification must be an Attribute

### ISSUE THREAD

**Issue by F5Rob** [ldapjs/node-ldapjs#859]
New code version 3.0.1 produces an error that code version 2.4.4 does not. Can you please fix the latest version so the change with modification operation works. 

-----Error-----
```
Error: modification must be an Attribute
    at set modification [as modification] (/usr/src/ad-ephemeral-auth/node_modules/@ldapjs/change/index.js:55:13)
    at new Change (/usr/src/ad-ephemeral-auth/node_modules/@ldapjs/change/index.js:29:23)
    at /usr/src/ad-ephemeral-auth/index.js:275:3
    at Layer.handle [as handle_request] (/usr/src/ad-ephemeral-auth/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/ad-ephemeral-auth/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/src/ad-ephemeral-auth/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/src/ad-ephemeral-auth/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/ad-ephemeral-auth/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/usr/src/ad-ephemeral-auth/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/ad-ephemeral-auth/node_modules/express/lib/router/index.js:280:10)
```

----Change function-----
```js
app.get('/ldap_update', function(ldap_data, response) {
      
    // Attributes from iRule
    const ldap_dn = ldap_data.query.dn;
    const ldap_clearance = ldap_data.query.clearance;
    const ldap_date_time = ldap_data.query.date_time;
    const ldap_password = ldap_data.query.password;
	let bind_dn = ldap_data.query.bind_dn;
    let bind_pw = ldap_data.query.bind_pw;
    
    debuglog('Client IP: ' + ldap_data.ip + ' ldap_dn: ' + ldap_dn );
    debuglog('Client IP: ' + ldap_data.ip + ' ldap_clearance: ' + ldap_clearance);
    debuglog('Client IP: ' + ldap_data.ip + ' ldap_date_time: ' + ldap_date_time);
    debuglog('Client IP: ' + ldap_data.ip + ' ldap_password: ' + ldap_password);
	debuglog('Client IP: ' + ldap_data.ip + ' bind_dn: ' + bind_dn);
    debuglog('Client IP: ' + ldap_data.ip + ' bind_pw: ' + bind_pw);
    
    const modifyUser = [
		new ldap.Change({
			operation: 'replace',
			modification:{
				samlAssertionTime: [ldap_date_time],
			}
		}),
		new ldap.Change({
			operation: 'replace',
			modification:{
				clearance: [ldap_clearance],
			}
		}),
		new ldap.Change({
			operation: 'replace',
			modification:{
				unicodePwd: encodePassword(ldap_password),
			}
		})
	]		

    debuglog('Creating LDAP Client.');
   
    // Create LDAP Client
    const ldap_client = ldap.createClient({
        url: bind_url,
        tlsOptions: { 'rejectUnauthorized': false } // Ignore Invalid Certificate - Self Signed etc..
    });

    // Bind to the LDAP Server
    ldap_client.bind(bind_dn, bind_pw, function(req) {
        if (req) {
            debuglog('Error Binding to: ' + bind_url);
            response.json('{"error":"' + req + ' ldap client bind failed for ldap update"}'); // Bind Failed
            return;
        } else {
                debuglog('LDAP Bind Successful.');

                 ldap_client.modify(ldap_dn, modifyUser, function (req, res) {
                    if (req) {
                        debuglog('LDAP user update Error: ' + req);
                        ldap_unbind(ldap_client);
                        response.json('{"error":"' + req + ' ldap update failed for user ' + ldap_dn + '"}'); //Error
						return;
                    }
                    else {
                        debuglog('LDAP Modify Status:' + res);
                        ldap_unbind(ldap_client);
                        response.json('{"status":"user ' + ldap_dn + ' ldap update succeeded"}'); // No Error
						return;
                    }
                });
        }
    });
});
```

>

**Comment by jsumners** [comment]
I don't see a question being asked. What resolution are you looking for with this issue?

**Comment by F5Rob** [comment]
> I don't see a question being asked. What resolution are you looking for with this issue?

I updated my issue with a question for a resolution to the error.

**Comment by jsumners** [comment]
> Can you please fix the latest version so the change with modification operation works.

The "latest version" (3.x) _does_ support change with modification:

https://github.com/ldapjs/node-ldapjs/blob/9613308c331ec944029cd01b9039c593f1cdd214/test/client.test.js#L631-L683

See also:

https://github.com/ldapjs/messages/blob/b37b2f5fe400d09deea47103f609a8c29a86452d/lib/messages/modify-request.test.js#L68-L79

**Comment by F5Rob** [comment]
> > Can you please fix the latest version so the change with modification operation works.
> 
> The "latest version" (3.x) _does_ support change with modification:
> 
> https://github.com/ldapjs/node-ldapjs/blob/9613308c331ec944029cd01b9039c593f1cdd214/test/client.test.js#L631-L683
> 
> See also:
> 
> https://github.com/ldapjs/messages/blob/b37b2f5fe400d09deea47103f609a8c29a86452d/lib/messages/modify-request.test.js#L68-L79

I am encountering an error with the new code that doesn’t happen in the previous version.

**Comment by jsumners** [comment]
> I am encountering an error with the new code that doesn’t happen in the previous version.

Have you adjusted your code as shown in the examples above?

**Comment by F5Rob** [comment]
> > I am encountering an error with the new code that doesn’t happen in the previous version.
> 
> Have you adjusted your code as shown in the examples above?

Apparently there was a change made and not included in the ldapjs.org documentation.
Version 2.4.4 code
-----
```
    const modifyUser = [
		new ldap.Change({
			operation: 'replace',
			modification:{
				samlAssertionTime: [ldap_date_time],
			}
		}),
		new ldap.Change({
			operation: 'replace',
			modification:{
				clearance: [ldap_clearance],
			}
		}),
		new ldap.Change({
			operation: 'replace',
			modification:{
				unicodePwd: encodePassword(ldap_password),
			}
		})
	]
```
-----
Modified code to work with ldapjs version 3.0.1
-----
```
const Attribute = require('@ldapjs/attribute')
    const modifyUser = [
		new ldap.Change({
			operation: 'replace',
			modification: new Attribute({
				type: 'samlAssertionTime',
				values: [ldap_date_time]
			})
		}),
		new ldap.Change({
			operation: 'replace',
			modification: new Attribute({
				type: 'clearance',
				values: [ldap_clearance]
			})
		}),
		new ldap.Change({
			operation: 'replace',
			modification: new Attribute({
				type: 'unicodePwd',
				values: encodePassword(ldap_password)
			})
		})
	]
```
-----
