### ISSUE TITLE
v3 server parser error with empty attribute name

### ISSUE THREAD

**Issue by ahaenggli** [ldapjs/node-ldapjs#867]
There are some third-party tools that query an LDAP server with an empty '' attribute name like in the client.js example below this issue.
Sometimes the user should have defined an attribute name for a specific value (e.g. which attribute should be used as login name or for admin privileges). Sometimes the query is just wrong, but unfortunately it can't be fixed as fast as hoped.

In v3.0.2 the server (example server.js also below) throws error `Attribute must be a valid string`. 

<details>
  <summary>log of server.js v3.0.2</summary>

```log
LDAP server up at: ldap://127.0.0.1:1389
TRACE: 2023-04-01T11:02:21.947Z:  new connection from %s 127.0.0.1:62715
TRACE: 2023-04-01T11:02:21.949Z:  data on %s: %s 127.0.0.1:62715 <Buffer 30 84 00 00 00 10 02 01 39 60 84 00 00 00 07 02 01 03 04 00 80 00>
DEBUG: 2023-04-01T11:02:21.954Z:  %s: message received: req=%j 127.0.0.1:62715 {
  messageId: 57,
  protocolOp: 96,
  type: 'BindRequest',
  version: 3,
  name: '',
  authenticationType: 'simple',
  credentials: '',
  controls: []
}
DEBUG: 2023-04-01T11:02:21.958Z:  %s: sending: %j 127.0.0.1:62715 { status: 0, matchedDN: '', diagnosticMessage: '', referrals: [] }
TRACE: 2023-04-01T11:02:21.959Z:  data on %s: %s 127.0.0.1:62715 <Buffer 30 84 00 00 00 91 02 01 3a 63 84 00 00 00 56 04 10 64 63 3d 64 6f 6d 61 69 6e 2c 64 63 3d 74 6c 64 0a 01 02 0a 01 00 02 01 00 02 01 78 01 01 00 a0 84 ... 101 more bytes>
ERROR: 2023-04-01T11:02:21.964Z:  server.js !!! error !!! VError: Parser error for 127.0.0.1:62715: attribute must be a valid string
    at Parser.<anonymous> (C:\tmp\node_modules\ldapjs\lib\server.js:459:26)
    at Parser.emit (node:events:513:28)
    at Parser.write (C:\tmp\node_modules\ldapjs\lib\messages\parser.js:131:10)
    at Socket.<anonymous> (C:\tmp\node_modules\ldapjs\lib\server.js:474:19)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  jse_shortmsg: 'Parser error for 127.0.0.1:62715',
  jse_cause: Error: attribute must be a valid string
      at set attributes [as attributes] (C:\tmp\node_modules\@ldapjs\messages\lib\messages\search-request.js:202:15)
      at new SearchRequest (C:\tmp\node_modules\@ldapjs\messages\lib\messages\search-request.js:151:21)
      at parseToMessage (C:\tmp\node_modules\@ldapjs\messages\lib\parse-to-message.js:61:19)
      at LdapMessage.parse (C:\tmp\node_modules\@ldapjs\messages\lib\ldap-message.js:262:41)
      at Parser.write (C:\tmp\node_modules\ldapjs\lib\messages\parser.js:117:38)
      at Socket.<anonymous> (C:\tmp\node_modules\ldapjs\lib\server.js:474:19)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10),
  jse_info: {},
  cause: [Function: ve_cause]
}
TRACE: 2023-04-01T11:02:21.966Z:  %s close; had_err=%j 127.0.0.1:62715 false

```

</details>

In version 2.3.3, the server did not throw an error message and processed the request as shown in this log:

<details>
<summary>log of server.js v2.3.3</summary>

```log
LDAP server up at: ldap://127.0.0.1:1389
TRACE: 2023-04-01T11:03:14.950Z:  new connection from %s 127.0.0.1:62792
TRACE: 2023-04-01T11:03:14.952Z:  data on %s: %s 127.0.0.1:62792 <Buffer 30 84 00 00 00 10 02 01 3d 60 84 00 00 00 07 02 01 03 04 00 80 00>
TRACE: 2023-04-01T11:03:14.952Z:  parse: data=%s <Buffer 02 01 03 04 00 80 00>
TRACE: 2023-04-01T11:03:14.953Z:  Parsing done: %j {
  messageID: 61,
  protocolOp: 'BindRequest',
  version: 3,
  name: '',
  authenticationType: 'simple',
  credentials: '',
  controls: []
}
DEBUG: 2023-04-01T11:03:14.955Z:  %s: message received: req=%j 127.0.0.1:62792 {
  messageID: 61,
  protocolOp: 'BindRequest',
  version: 3,
  name: '',
  authenticationType: 'simple',
  credentials: '',
  controls: []
}
DEBUG: 2023-04-01T11:03:14.957Z:  %s: sending:  %j 127.0.0.1:62792 {
  messageID: 61,
  protocolOp: 'LDAPResult',
  status: 0,
  matchedDN: '',
  errorMessage: '',
  referrals: [],
  controls: []
}
TRACE: 2023-04-01T11:03:14.958Z:  data on %s: %s 127.0.0.1:62792 <Buffer 30 84 00 00 00 91 02 01 3e 63 84 00 00 00 56 04 10 64 63 3d 64 6f 6d 61 69 6e 2c 64 63 3d 74 6c 64 0a 01 02 0a 01 00 02 01 00 02 01 78 01 01 00 a0 84 ... 101 more bytes>
TRACE: 2023-04-01T11:03:14.958Z:  parse: data=%s <Buffer 04 10 64 63 3d 64 6f 6d 61 69 6e 2c 64 63 3d 74 6c 64 0a 01 02 0a 01 00 02 01 00 02 01 78 01 01 00 a0 84 00 00 00 23 a4 84 00 00 00 10 04 03 75 69 64 ... 86 more bytes>
TRACE: 2023-04-01T11:03:14.960Z:  Parsing done: %j {
  messageID: 62,
  protocolOp: 'SearchRequest',
  baseObject: 'dc=domain,dc=tld',
  scope: 'sub',
  derefAliases: 0,
  sizeLimit: 0,
  timeLimit: 120,
  typesOnly: false,
  filter: '(&(objectclass=*))',
  attributes: [ 'dn', '' ],
  controls: [
    PagedResultsControl {
      _value: [Object],
      type: '1.2.840.113556.1.4.319',
      criticality: false
    }
  ]
}
DEBUG: 2023-04-01T11:03:14.961Z:  %s: message received: req=%j 127.0.0.1:62792 {
  messageID: 62,
  protocolOp: 'SearchRequest',
  baseObject: 'dc=domain,dc=tld',
  scope: 'sub',
  derefAliases: 0,
  sizeLimit: 0,
  timeLimit: 120,
  typesOnly: false,
  filter: '(&(objectclass=*))',
  attributes: [ 'dn', '' ],
  controls: [
    PagedResultsControl {
      _value: [Object],
      type: '1.2.840.113556.1.4.319',
      criticality: false
    }
  ]
}
LOG: 2023-04-01T11:03:14.963Z:  server.search Search for => DN: dc=domain,dc=tld; Scope: sub; Filter: (&(objectclass=*)); Attributes: dn,;
DEBUG: 2023-04-01T11:03:14.963Z:  %s: sending:  %j 127.0.0.1:62792 {
  messageID: 62,
  protocolOp: 'LDAPResult',
  status: 0,
  matchedDN: '',
  errorMessage: '',
  referrals: [],
  controls: []
}

```

</details>

The thrown error makes absolute sense in the client part of ldapjs. However, on the server side it would be better to be able to handle the queries. I am wavering between:
- Accept empty attribute names as well
- Just ignore empty attribute names instead of throwing the error

Probably the latter would be the nicer solution. What do you think about that?

Mentioned examples:
<details>
  <summary>server.js</summary>

```node
'use strict';
const ldap = require('ldapjs');

const log = console.log;
const error = console.error;
const warn = console.warn;

const logger = {
    debug: function () { log.apply(console, ['DEBUG: ' + new Date().toISOString() + ": "].concat(Array.prototype.slice.call(arguments))); },
    trace: function () { log.apply(console, ['TRACE: ' + new Date().toISOString() + ": "].concat(Array.prototype.slice.call(arguments))); },
    error: function () { error.apply(console, ['ERROR: ' + new Date().toISOString() + ": "].concat(Array.prototype.slice.call(arguments))); },
    warn: function () { warn.apply(console, ['WARN: ' + new Date().toISOString() + ": "].concat(Array.prototype.slice.call(arguments))); },
    log: function () { log.apply(console, ['LOG: ' + new Date().toISOString() + ": "].concat(Array.prototype.slice.call(arguments))); },
};

const srvOptions = {};
srvOptions.log = logger;

const server = ldap.createServer(srvOptions);

const SUFFIX = '';
const db = {
    "dc=domain,dc=tld": {
        "objectClass": "domain",
        "dc": "domain",
        "entryDN": "dc=domain,dc=tld",
        "namingContexts": "dc=domain,dc=tld",
        "structuralObjectClass": "domain",
        "subschemaSubentry": "cn=subschema",
        "creatorsName": "uid=root,cn=users,dc=domain,dc=tld",
        "modifiersName": "uid=root,cn=users,dc=domain,dc=tld"
    },
    "cn=users,dc=domain,dc=tld": {
        "objectClass": "organizationalRole",
        "cn": "users",
        "entryDN": "cn=users,dc=domain,dc=tld",
        "hasSubordinates": "TRUE",
        "subschemaSubentry": "cn=subschema",
        "creatorsName": "uid=root,cn=users,dc=domain,dc=tld",
        "modifiersName": "uid=root,cn=users,dc=domain,dc=tld"
    }
};

server.bind(SUFFIX, (req, res, next) => {
    logger.log('server.bind', req);
    res.end();
    return next();
});

server.search(SUFFIX, (req, res, next) => {
    const dn = req.dn.toString().toLowerCase().replace(/ /g, '');
    logger.log('server.search', 'Search for => DN: ' + dn + '; Scope: ' + req.scope + '; Filter: ' + req.filter + '; Attributes: ' + req.attributes + ';');
    res.end();
    return next();
});

server.on("error", (error) => {
    logger.error("server.js", "!!! error !!!", error);
});

server.on("uncaughtException", (error) => {
    logger.error("server.js", "!!! uncaughtException !!!", error);
});

server.listen(1389, "127.0.0.1", () => {
    console.log('LDAP server up at: %s', server.url);
});
```

</details>
<details>
  <summary>client.js</summary>

```node 
'use strict';
const ldap = require('ldapjs');

const client = ldap.createClient({ url: ['ldap://127.0.0.1:1389'] });
const opts = {
    filter: '(&(objectClass=*))',
    scope: 'sub',
    attributes: ['dn', '']
};

client.search('dc=domain,dc=tld', opts, (err, res) => {
    res.on('searchRequest', (searchRequest) => {
        console.log('client.search', 'searchRequest: ', searchRequest.messageId);
    });
    res.on('searchEntry', (entry) => {
        console.log('client.search', 'entry: ' + JSON.stringify(entry.object));
    });
    res.on('searchReference', (referral) => {
        console.log('client.search', 'referral: ' + referral.uris.join());
    });
    res.on('error', (err) => {
        console.error('client.search', 'error: ' + err.message);
    });
    res.on('end', (result) => {
        console.log('client.search', 'status: ' + result.status);
    });
});
```

</details>

**Comment by jsumners** [comment]
My understanding of the spec, summarized at https://ldap.com/ldapv3-wire-protocol-reference-search/#search-request-attributes, is that an empty attribute string is not allowed:

https://www.rfc-editor.org/rfc/rfc4511#section-4.5.1.8
> attributeSelector = attributedescription / selectorspecial
> The <attributedescription> production is defined in Section 2.5 of
      [RFC4512].

https://www.rfc-editor.org/rfc/rfc4512#section-2.5
> An attribute description is composed of an attribute type (see
   [Section 2.5.1](https://www.rfc-editor.org/rfc/rfc4512#section-2.5.1)) and a set of zero or more attribute options (see
   [Section 2.5.2](https://www.rfc-editor.org/rfc/rfc4512#section-2.5.2)).
> [...snip...]
> Examples of valid attribute descriptions:
>
>      2.5.4.0
>      cn;lang-de;lang-en
>      owner

Is your suggestion that `@ldapjs/messages` be altered to ignore empty string attribute names?

**Comment by ahaenggli** [comment]
My understanding of the spec is the same.
Strictly speaking, it seems to me now even more accurately implemented in ldapjs than in other servers... But unfortunately not all 3rd party applications can handle it this way :(

Exactly. In `@ldapjs/messages` you could use e.g. 
```node
  set attributes(attrs) {
    if (Array.isArray(attrs) === false) {
      throw Error('attributes must be an array of attribute strings')
    }
    attrs = attrs.filter(n => n)
   ...
```
If it helps, I could gladly prepare a PR (of course with extension of a specific test).

**Comment by jsumners** [comment]
I've been mulling this over. I really don't want to deviate from the spec, because that makes maintenance easy (e.g. "requested X does not follow the spec"). However, in this case, since clients seem to be violating the spec due to servers allowing it, I am willing to accept a change that looks like:

```js
if (attr.type === '') {
  // TODO: emit warning about spec violation via log and/or telemetry

  warning.emit('LDAP_ATTRIBUTE_SPEC_ERR_001')
  // 'received attempt to define attribute with an empty name: attribute skipped'

  return
}
```

Eventually we should be instrumenting the libraries with OpenTelemetry, but we need their JS system to stabilize and for `@ldapjs/server` & `@ldapjs/client` to be created first.

**Comment by jsumners** [comment]
Thank you for contributing the solution. `@ldapjs/messages@1.1.0` has been published. Update your dependencies to start using the fix.
