### ISSUE TITLE
TypeError: Cannot destructure property 'message' of 'tracker.fetch(...)' as it is null

### ISSUE THREAD

**Issue by benzhuo** [ldapjs/node-ldapjs#897]
ldapjs 3.0.2, node.js version: v18.12.1

I have met the issue in my production ENV and trying to reproduced in my dev Env.

-----------------------------------------------------------------
/app/node_modules/ldapjs/lib/client/client.js:884
      const { message: trackedMessage, callback } = tracker.fetch(message.messageId)
                       ^
TypeError: Cannot destructure property 'message' of 'tracker.fetch(...)' as it is null.
    at Parser.onMessage (/app/node_modules/ldapjs/lib/client/client.js:884:24)
    at Parser.emit (node:events:513:28)
    at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:135:8)
    at TLSSocket.onData (/app/node_modules/ldapjs/lib/client/client.js:875:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)

---------------------------------------------------------------------
In index.js line 91
function ** tracker.fetch ** returns null if neither tracked==true nor abandonedMsg==true
which will cause line 884 in client.js crash
const { message: trackedMessage, callback } = tracker.fetch(message.messageId)

TypeError: Cannot destructure property 'message' of 'tracker.fetch(...)' as it is null.

**Comment by benzhuo** [comment]
[duplicated issue but closed](https://github.com/ldapjs/node-ldapjs/issues/890)

**Comment by benzhuo** [comment]
The same function in v2.2.3 should have not same issue 

    // The "router"
    tracker.parser.on('message', function onMessage (message) {
      message.connection = self._socket
      const callback = tracker.fetch(message.messageID)

      if (!callback) {
        log.error({ message: message.json }, 'unsolicited message')
        return false
      }

      return callback(message)
    })

**Comment by jsumners** [comment]
Please do not open multiple issues for the same problem.
