### ISSUE TITLE
Unable to perform add operation against LDAP server.

### ISSUE THREAD

**Issue by afontalv** [ldapjs/node-ldapjs#898]
Hi team,

Thank you in advance for the assistance, sincerely appreciate the help.

We have an ldapjs client connecting to an AD server through ldap over ssl (ldaps). Whenever we try to add a new object, we get the below error:

```
EntryAlreadyExistsError: 00002071: UpdErr: DSID-030503CF, problem 6005 (ENTRY_EXISTS), data 0
    at messageCallback (C:\Users\app\node_modules\ldapjs\lib\client\client.js:1220:45)
    at Parser.onMessage (C:\Users\app\node_modules\ldapjs\lib\client\client.js:888:14)
    at Parser.emit (node:events:520:28)
    at Parser.write (C:\Users\app\node_modules\ldapjs\lib\messages\parser.js:107:8)
    at TLSSocket.onData (C:\Users\app\node_modules\ldapjs\lib\client\client.js:875:22)
    at TLSSocket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

The error indicates the user we are trying to add already exists. However, if I were to look up the user in AD, I wouldn't find them.

Any advice is greatly welcomed. 

Thank you 

Here is the code snippet on how the ldapjs client is configured:

```javascript
'use strict';

import config from './config.js';
import ldap from 'ldapjs';
import { readFileSync } from 'fs';
import path from 'path';

const ldapDc = 'ldaps://'+ config.ad.host + ':' + config.ad.port

// Location of SSL certificate used to securely connect with AD server
const sslCertLoc = path.join(process.cwd(), '/app/certs/ca.crt');

var ldapConn = ldap.createClient({
    url: ldapDc,
    timeout: 10000, // in milliseconds
    reconnect: true, // Try to reconnect when the connection is lost
    tlsOptions: {
        ca: [ readFileSync(sslCertLoc) ]
    }
});

ldapConn.bind(config.ad.clientId, config.ad.clientSecret, (err) => {
    if (err) {
        console.error('There was an error while establishing OnPrem AD Connection:')
        console.error(err)
        throw err;
    }
});

const display_name = `Mickey Mouse`
const ou= 'OU=Users, OU=earth, DC=adname, DC=orgname, DC=org'

// user entry
const entry = {
    distinguishedName: `cn=${display_name}, ${ou}`,
    displayName: display_name,
    sAMAccountName: 'mmouse', 
    cn: display_name,
    name: display_name,
    sn: 'Mouse',
    givenName: 'Mickey,
    userPrincipalName: 'mmouse@domain.org', 
    mail: 'mmouse@domain.org',
    co: 'United States',
    company: 'MyFancyOrg',
    physicalDeliveryOfficeName: 'Boston, United States',
    department: 'Entertainment',
    title: 'Engineer',
    unicodePwd: Buffer.from('"' + 'MyAw3s0m3P@$w0rD!' + '"', 'utf16le').toString(),
    objectclass: 'user',
    description: (new Date()).toLocaleString() + ' - [AutoProcessing] - New account created'
};

ldapConn.add(ou, entry, (err) => {
    if (err) {
        console.log(err);
        reject({
            response: {
                status: 400, message: errors.UNABLE_TO_CREATE_USER
            }
        });
    } else {
        resolve('success');
    }
});
```

**Comment by jsumners** [comment]
The error comes from the server, so it's not an issue with this library. I would suggest investigating the permissions of the user your using to perform the `ADD` operation. It is possible that the error message is misleading and that the actual error is a permissions error.

Also, make sure that the path of the entry is to the new entity and not the parent OU.

**Comment by afontalv** [comment]
Hello @jsumners, thank you for your quick response!

Just checked the permissions of the user I'm using to perform the `ADD` operation. The user has administrator permission: 
![image](https://github.com/ldapjs/node-ldapjs/assets/100861162/fb55a725-c1ac-4a73-b54b-3f64a031b8ce)

For troubleshooting purposes, I tried adding a new user directly by remote connecting to the AD server, and was able to add the user object without issues. 

Are there any other recommendations as to what could be the caused?

Thank you for your assistance :)

**Comment by jsumners** [comment]
> Also, make sure that the path of the entry is to the new entity and not the parent OU.

```js
const ou= 'OU=Users, OU=earth, DC=adname, DC=orgname, DC=org'
```

^ is the path to the parent OU, not the entry being added.

See https://github.com/ldapjs/node-ldapjs/blob/f2890088e49c0c7b7b880998d73d6e4a448d7b4e/test/client.test.js#L510-L521

**Comment by afontalv** [comment]
@jsumners AHHHH! You just brought so much happiness to this person!!!! It worked! Ah!!!! I am so happy! It's times like this I love developing software! It's always small details like this that get you! 

Thank you, thank you, thank YOU!!!! I am very grateful for your existence, for being so helpful, and for taking the time to read through this problem I was facing and providing a solution that was able to resolve the issue! 

Thank you friend!

**Comment by afontalv** [comment]
@jsumners AHHHH! You just brought so much happiness to this person!!!! It worked! Ah!!!! I am so happy! It's times like this I love developing software! It's always small details like this that get you!

Thank you, thank you, thank YOU!!!! I am very grateful for your existence, for being so helpful, and for taking the time to read through this problem I was facing and providing a solution that was able to resolve the issue!

Thank you friend!

**Comment by jsumners** [comment]
Technically, I live in the metro area. But I'd be much more comfortable with a contribution https://github.com/sponsors/jsumners

**Comment by jsumners** [comment]
Thank you. Your contribution means a lot to me right now ❤️
