### ISSUE TITLE
modification must be an Attribute

### ISSUE THREAD

**Issue by RayllanSouza** [ldapjs/node-ldapjs#903]
Boa tarde.

Estou iniciando com o modulo, e seguindo os exemplos de código para mudança de senhas que vejo na internet e sempre recebo o seguinte erro:

```
Error: modification must be an Attribute
    at set modification [as modification] (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\@ldapjs\change\index.js:55:13)
    at new Change (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\@ldapjs\change\index.js:29:23)
    at C:\Users\rayllan.souza\Desktop\ldapjs\index.js:24:17
    at Layer.handle [as handle_request] (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\express\lib\router\index.js:280:10)
(node:313580) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

Segue codigo:

```
function modifyPassword(userDN, oldPassword, newPassword) {

    const ldapClient = ldap.createClient({url: "ldap://meudominio.local:389"})
    return new Promise((resolve, reject) => {
 
     try {
       ldapClient.bind("usuarioADM", "senhaADM", err => {
         if (err) {
           reject(err);
         }
 
         ldapClient.modify(userDN, [
           new ldap.Change({
             operation: 'delete',
             modification: {
               unicodePwd: encodePassword(oldPassword)
             }
           }),
           new ldap.Change({
             operation: 'add',
             modification: {
               unicodePwd: encodePassword(newPassword)
             }
           })
         ], (error) => {
           if (error) {
             reject(error);
           } else {
             resolve('Successfully password modified.');
           }
         });
       })
     } catch (error) {
       console.error(error);
       reject(error);
 
        }
       })
 }
```

**Comment by jsumners** [comment]
I think this is a duplicate of #865. Please use English for issue reports.

**Comment by RayllanSouza** [comment]
OK sorry. Even after performing the "duplicate" procedures I still get the error. I don't know where the error is

**Comment by jsumners** [comment]
I do not understand what you mean by "the duplicate procedures". What changes did you make to the code sample you provided that still result in the error?

**Comment by RayllanSouza** [comment]
Sorry for the "duplicate procedures", it's just that I don't communicate very well using English, I made the change incorrectly, but now after making the change I get a new error.
He follows:

```
C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\@ldapjs\dn\lib\utils\parse-string\read-attribute-value.js:34
    throw Error('attribute value does not start with equals sign')
    ^

Error: attribute value does not start with equals sign
    at readAttributeValue (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\@ldapjs\dn\lib\utils\parse-string\read-attribute-value.js:34:11)
    at readAttributePair (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\@ldapjs\dn\lib\utils\parse-string\read-attribute-pair.js:62:27)
    at parseString (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\@ldapjs\dn\lib\utils\parse-string\index.js:66:32)
    at DN.fromString (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\@ldapjs\dn\lib\dn.js:331:18)
    at ensureDN (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\ldapjs\lib\client\client.js:85:15)
    at Client.modify (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\ldapjs\lib\client\client.js:473:13)
    at C:\Users\rayllan.souza\Desktop\ldapjs\index.js:30:21
    at Client.callbackWrapper (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\ldapjs\lib\client\client.js:296:5)
    at Client.emit (node:events:511:28)
    at Socket.onResult (C:\Users\rayllan.souza\Desktop\ldapjs\node_modules\ldapjs\lib\client\client.js:812:14)
```

Code:


```
    return new Promise((resolve, reject) => {
 
     try {
      ldapClient.bind("usuarioADM", "senhaADM", err => {
         if (err) {
           reject(err);
         }
 
         ldapClient.modify(user, [
           new ldap.Change({
             operation: 'replace',
             modification: {
              type: "unicodePwd",
              values: [encodePassword(newpassword)]
             }
           })
         ], (error) => {
           if (error) {
             reject(error);
           } else {
             resolve('Successfully password modified.');
           }
         });
       })
      }catch (error) {
       console.error(error);
       reject(error);
 
      }
    })
```

**Comment by jsumners** [comment]
What is `encodePassword`? Does it return a string? What is the value of `user`? Is it a DN string pointing to the entity to be changed?

Please see https://github.com/ldapjs/node-ldapjs/blob/f2890088e49c0c7b7b880998d73d6e4a448d7b4e/test/client.test.js#L661-L683

**Comment by RayllanSouza** [comment]
What is encodePassword? 
**R:** Yes, return string;
What is the value of user? 
**R:** Yes, return cn=user

After checking the code you sent I was able to review some things I was doing wrong, but now I get the error "Invalid Credentials" on the bind method even with the correct username and password

**Comment by jsumners** [comment]
Your example shows a simple username and password combination. Standard LDAP servers require the "username" be a DN string pointing to the user entity in the directory.

**Comment by RayllanSouza** [comment]
Ok, I added the correct line and the error is gone. Operations error only occurs now, can you tell me if it can be user permission in the domain? I'm trying to create a tool that resets the password of a third-party user, this user who has the name "reset" was given permission to change the password of other users only, he does not have administrator permissions.

**Comment by jsumners** [comment]
I'm sorry, but I cannot tell you anything about the configuration of your LDAP server. I am closing this because we have covered all of the issues that pertain to usage of the ldapjs library.
